packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  prisma: true
  protobufjs: false
  tesseract.js: true
  unrs-resolver: true
